services:
  backend:
    profiles: [ci, backend]
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3100:3100"
    environment:
      PORT: 3100
      DATABASE_NAME: "petin"
      DATABASE_URL: "postgres://postgres:password@postgres:5432/petin"
      AUTH_TOKEN_SECRET: "a87a8411da267ddb131c5ba79a0f82f10532e106656886f739f09f35dc045e335da9838fac1965cf7b0f6ac8153ae7c2ebc8bddf6bb8cd582aba54128a063d7368a3a9863438c6b914821d2e3d128f0a7d2c07b1b0d41376ec7bb744ab9401a333618a498b4fe70bd9c8ff37efbeeb8d161599c2c590d2bc86e19426f098de5277bd3ff252eb6816da188e4a7581bf6e75c6dbba0a8a2707debb73c7dc85307a24d2514c55624b780315712770fba682098b37e29f5865e7dfb7faa050c0197657b7dcd6eaa6dcbba79765b8b7ce8191eecb8704d9a68a05e24ef0632a1a58fd36fd5f5b6c7abdf8b27d7cf8d2581d3f4757a6b2827b68f841c202ef02b96af6"
      MESSAGE_BROKER_URL: "amqp://rabbit:rabbit@rabbitmq:5672"
    # healthcheck:
    #   # test: curl --fail http://localhost:3100/health || exit 1
    #   test: wget --no-verbose --tries=1 --spider http://backend:3100/health || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 10s
    links:
      - postgres
      - rabbitmq

  postgres:
    profiles: [ci, backend, dev, db]
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: "petin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      # ALLOW_EMPTY_PASSWORD: "yes"
    # healthcheck:
    #   test: pg_isready -U postgres
    #   interval: 5s
    #   retries: 6
    #   start_period: 1s
    volumes:
      - ./.docker/postgresql:/bitnami/postgresql
      - ./backend/scripts/create_petin.sql:/docker-entrypoint-initdb.d/init.sql
      
  pg-admin:
    profiles: [dev, db]
    image: dpage/pgadmin4
    ports: 
      - "8081:80"
    volumes:
      - ./.docker/pgadmin:/var/lib/pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    links:
      - postgres

  rabbitmq:
    profiles: [ci, backend, dev, mq]
    image: bitnami/rabbitmq:latest
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=no
      - RABBITMQ_LOGS=-
      - RABBITMQ_USERNAME=rabbit
      - RABBITMQ_PASSWORD=rabbit
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    volumes:
      - './.docker/rabbitmq:/bitnami/rabbitmq/mnesia'
    