version: '2'
services:   
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: "petin"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    networks:
      - app-network
    volumes:
      - ./.docker/dbdata/postgres:/var/lib/postgresql

  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4
    ports: 
      - "8081:80"
    depends_on: 
      - postgres
    volumes:
      - ./.docker/dbdata/pgadmin:/var/lib/pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
