// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PetinAccount struct {
	ID         int64            `json:"id"`
	ExternalID string           `json:"external_id"`
	Email      string           `json:"email"`
	Password   string           `json:"password"`
	Status     string           `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type PetinAddress struct {
	ID           int64            `json:"id"`
	ExternalID   string           `json:"external_id"`
	AddressLine  string           `json:"address_line"`
	StreetNumber string           `json:"street_number"`
	City         string           `json:"city"`
	State        string           `json:"state"`
	CountryCode  string           `json:"country_code"`
	ZipCode      string           `json:"zip_code"`
	Latitude     pgtype.Numeric   `json:"latitude"`
	Longitude    pgtype.Numeric   `json:"longitude"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
