// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (PetinAccount, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (PetinAddress, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (PetinProfile, error)
	GetAccount(ctx context.Context, externalID string) (PetinAccount, error)
	GetAccountByEmail(ctx context.Context, email string) (PetinAccount, error)
	GetProfileByAccountExternalID(ctx context.Context, externalID string) (GetProfileByAccountExternalIDRow, error)
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (PetinAccount, error)
}

var _ Querier = (*Queries)(nil)
