// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (PetinAccount, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccountByEmail(ctx context.Context, email string) (PetinAccount, error)
	GetAccountByExternalId(ctx context.Context, externalID string) (PetinAccount, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (PetinAccount, error)
}

var _ Querier = (*Queries)(nil)
