// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO petin.account (external_id, email, password, status)
VALUES ($1, $2, $3, $4)
RETURNING id, external_id, email, password, status, created_at, updated_at
`

type CreateAccountParams struct {
	ExternalID string `json:"external_id"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	Status     string `json:"status"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (PetinAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ExternalID,
		arg.Email,
		arg.Password,
		arg.Status,
	)
	var i PetinAccount
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM petin.account WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, external_id, email, password, status, created_at, updated_at FROM petin.account WHERE email = $1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (PetinAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i PetinAccount
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByExternalId = `-- name: GetAccountByExternalId :one
SELECT id, external_id, email, password, status, created_at, updated_at FROM petin.account WHERE external_id = $1
`

func (q *Queries) GetAccountByExternalId(ctx context.Context, externalID string) (PetinAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByExternalId, externalID)
	var i PetinAccount
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE petin.account SET email = $2, password = $3, status = $4 WHERE id = $1 RETURNING id, external_id, email, password, status, created_at, updated_at
`

type UpdateAccountParams struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Status   string `json:"status"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (PetinAccount, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Status,
	)
	var i PetinAccount
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
