// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	ConfirmHandover(ctx context.Context, arg ConfirmHandoverParams) (PetinHandover, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (PetinAccount, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (PetinAddress, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (PetinConversation, error)
	CreateHandover(ctx context.Context, arg CreateHandoverParams) (PetinHandover, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (PetinMessage, error)
	CreatePet(ctx context.Context, arg CreatePetParams) (PetinPet, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (PetinProfile, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (PetinReport, error)
	GetAccount(ctx context.Context, externalID string) (PetinAccount, error)
	GetAccountByEmail(ctx context.Context, email string) (PetinAccount, error)
	GetAvailablePetsNearby(ctx context.Context, arg GetAvailablePetsNearbyParams) ([]GetAvailablePetsNearbyRow, error)
	GetConversation(ctx context.Context, externalID string) (PetinConversation, error)
	GetConversationByID(ctx context.Context, id int64) (PetinConversation, error)
	GetConversationsByProfileID(ctx context.Context, adopterProfileID int64) ([]PetinConversation, error)
	GetHandover(ctx context.Context, externalID string) (PetinHandover, error)
	GetHandoversByProfileID(ctx context.Context, ownerProfileID int64) ([]PetinHandover, error)
	GetMessagesByConversationID(ctx context.Context, conversationID int64) ([]PetinMessage, error)
	GetPet(ctx context.Context, externalID string) (PetinPet, error)
	GetPetByID(ctx context.Context, id int64) (PetinPet, error)
	GetPetsByProfileID(ctx context.Context, profileID int64) ([]PetinPet, error)
	GetProfileByAccountExternalID(ctx context.Context, externalID string) (GetProfileByAccountExternalIDRow, error)
	GetReport(ctx context.Context, externalID string) (PetinReport, error)
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (PetinAccount, error)
	UpdateHandoverLocation(ctx context.Context, arg UpdateHandoverLocationParams) (PetinHandover, error)
	UpdateHandoverScheduledDate(ctx context.Context, arg UpdateHandoverScheduledDateParams) (PetinHandover, error)
	UpdatePet(ctx context.Context, arg UpdatePetParams) (PetinPet, error)
	UpdatePetAvailability(ctx context.Context, arg UpdatePetAvailabilityParams) (PetinPet, error)
	UpdatePetCurrentOwner(ctx context.Context, arg UpdatePetCurrentOwnerParams) (PetinPet, error)
}

var _ Querier = (*Queries)(nil)
